In [136]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [137]:
data = pd.read_csv("Data.csv", delimiter = ",")

In [138]:
data.head()

sex  age   Time  Number_of_Warts  Type  Area  induration_diameter  y
0    1   22   2.25               14     3    51                   50  1
1    1   15   3.00                2     3   900                   70  1
2    1   16  10.50                2     1   100                   25  1
3    1   27   4.50                9     3    80                   30  1
4    1   20   8.00                6     1    45                    8  1

In [139]:
x = data.drop(["y"], axis = 1)
x.head()

sex  age   Time  Number_of_Warts  Type  Area  induration_diameter
0    1   22   2.25               14     3    51                   50
1    1   15   3.00                2     3   900                   70
2    1   16  10.50                2     1   100                   25
3    1   27   4.50                9     3    80                   30
4    1   20   8.00                6     1    45                    8

In [140]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   sex                  90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 90 non-null     float64
 3   Number_of_Warts      90 non-null     int64  
 4   Type                 90 non-null     int64  
 5   Area                 90 non-null     int64  
 6   induration_diameter  90 non-null     int64  
 7   y                    90 non-null     int64  
dtypes: float64(1), int64(7)
memory usage: 5.8 KB


In [141]:
y = data["y"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: y, dtype: int64

In [142]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state = 123)

In [143]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [144]:
knn = KNeighborsClassifier(n_neighbors =4)

In [145]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [146]:
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [147]:
knn.predict_proba(x_test)

array([[0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.  , 1.  ]])

In [148]:
print(confusion_matrix(y_test, y_pred))

[[ 1  3]
 [ 2 12]]


In [149]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.33      0.25      0.29         4
           1       0.80      0.86      0.83        14

    accuracy                           0.72        18
   macro avg       0.57      0.55      0.56        18
weighted avg       0.70      0.72      0.71        18

